service: serverless-aws
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - comprehend:*
          Resource: '*'
  
functions:
  analyse:
    handler: lambdas/endpoints/analyse.handler
    events:
      - http:
          path: analyse
          method: POST
          cors: true
